
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author bthn0
 */
public class Batuhan extends javax.swing.JFrame {

    Transactions t = new Transactions();
    static int mod;
    /**
     * Creates new form Batuhan
     */
    public Batuhan() {
        
        initComponents();
        Object[] options = {
            "CPU-CPU",
            "İnsan-CPU"};
        mod = JOptionPane.showOptionDialog(new JFrame(),
                "Oyunun Modunu Seçiniz",
                "Mod Seçimi",
                JOptionPane.YES_NO_CANCEL_OPTION,
                JOptionPane.INFORMATION_MESSAGE,
                null,
                options,
                options[1]);
        if (mod == -1) {//kullanıcı seçim yapmadan kapatırsa
            System.exit(0);
        }
        
        t.kartlariOlustur();//pokemon kartları tanımlanıyor.
        Oyuncu oyuncu1 = null;
        Oyuncu oyuncu2 = null;
        if(mod==0){
            oyuncu1 = new BilgisayarOyuncusu("Bilgisayar-1", 1, 0);
            oyuncu2 = new BilgisayarOyuncusu("Bilgisayar-2", 2, 0);
            kullanici1Ismi.setText("Bilgisayar-1");
            kullanici2Ismi.setText("Bilgisayar-2");
        }
        else if(mod==1){
            String isim ="Kullanıcı";
            isim = JOptionPane.showInputDialog("Oyuncunun İsmini Girin");
            oyuncu1 = new InsanOyuncusu(isim, 1, 0);
            oyuncu2 = new BilgisayarOyuncusu("Bilgisayar", 2, 0);
            kullanici1Ismi.setText(isim);
            kullanici2Ismi.setText("Bilgisayar");
        }
        t.basKartAta(t.kullanilanKartlar, t.pokemon, oyuncu1);
        t.basKartAta(t.kullanilanKartlar, t.pokemon, oyuncu2);
        //System.out.println(t.pokemon.get(0).getPokemonAdi());
        ImageIcon imageIcon1 = new ImageIcon(new ImageIcon("../cards/Bulbasaur"+".png").getImage().getScaledInstance(150, 200, Image.SCALE_DEFAULT));
        ImageIcon imageIcon2 = new ImageIcon(new ImageIcon("../cards/Batu"+".png").getImage().getScaledInstance(150, 200, Image.SCALE_DEFAULT));
        kullanici1OrtaKart.setIcon(imageIcon1);
        kullanici2OrtaKart.setIcon(imageIcon2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        ProgressBar1 = new javax.swing.JProgressBar();
        raundNext = new javax.swing.JButton();
        kullanici1Ismi = new javax.swing.JLabel();
        kullanici2Ismi = new javax.swing.JLabel();
        kullanici1Kart0 = new javax.swing.JPanel();
        kullanici1Kart1 = new javax.swing.JPanel();
        kullanici1Kart2 = new javax.swing.JPanel();
        kullanici1OrtaKart = new javax.swing.JLabel();
        kullanici2OrtaKart = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("SIRADAKİ RAUNT İÇİN KALAN SÜRE");

        raundNext.setText("ŞİMDİ GEÇ");
        raundNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                raundNextActionPerformed(evt);
            }
        });

        kullanici1Ismi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        kullanici1Ismi.setText("Kullanici-1");

        kullanici2Ismi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        kullanici2Ismi.setText("Kullanici-2");

        javax.swing.GroupLayout kullanici1Kart0Layout = new javax.swing.GroupLayout(kullanici1Kart0);
        kullanici1Kart0.setLayout(kullanici1Kart0Layout);
        kullanici1Kart0Layout.setHorizontalGroup(
            kullanici1Kart0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 135, Short.MAX_VALUE)
        );
        kullanici1Kart0Layout.setVerticalGroup(
            kullanici1Kart0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );

        kullanici1Kart1.setPreferredSize(new java.awt.Dimension(135, 150));

        javax.swing.GroupLayout kullanici1Kart1Layout = new javax.swing.GroupLayout(kullanici1Kart1);
        kullanici1Kart1.setLayout(kullanici1Kart1Layout);
        kullanici1Kart1Layout.setHorizontalGroup(
            kullanici1Kart1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 135, Short.MAX_VALUE)
        );
        kullanici1Kart1Layout.setVerticalGroup(
            kullanici1Kart1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );

        kullanici1Kart2.setPreferredSize(new java.awt.Dimension(135, 150));

        javax.swing.GroupLayout kullanici1Kart2Layout = new javax.swing.GroupLayout(kullanici1Kart2);
        kullanici1Kart2.setLayout(kullanici1Kart2Layout);
        kullanici1Kart2Layout.setHorizontalGroup(
            kullanici1Kart2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 135, Short.MAX_VALUE)
        );
        kullanici1Kart2Layout.setVerticalGroup(
            kullanici1Kart2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );

        kullanici1OrtaKart.setMaximumSize(new java.awt.Dimension(150, 200));
        kullanici1OrtaKart.setMinimumSize(new java.awt.Dimension(100, 100));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(310, 310, 310)
                .addComponent(kullanici1Kart0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(kullanici1Kart1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(kullanici1Kart2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 131, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(raundNext))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(kullanici1OrtaKart, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                    .addComponent(kullanici1Ismi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(kullanici2Ismi, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                    .addComponent(kullanici2OrtaKart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(337, 337, 337))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(raundNext, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(213, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(kullanici1Ismi, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kullanici2Ismi, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(kullanici1OrtaKart, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(kullanici2OrtaKart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(94, 94, 94)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(kullanici1Kart0, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kullanici1Kart1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kullanici1Kart2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void raundNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_raundNextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_raundNextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Batuhan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Batuhan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Batuhan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Batuhan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Batuhan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar ProgressBar1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel kullanici1Ismi;
    private javax.swing.JPanel kullanici1Kart0;
    private javax.swing.JPanel kullanici1Kart1;
    private javax.swing.JPanel kullanici1Kart2;
    private javax.swing.JLabel kullanici1OrtaKart;
    private javax.swing.JLabel kullanici2Ismi;
    private javax.swing.JLabel kullanici2OrtaKart;
    private javax.swing.JButton raundNext;
    // End of variables declaration//GEN-END:variables
}
